### ISSUE TITLE
Parsing errors (scss and js in html)

### ISSUE THREAD

**Issue by morleytatro** [UnwrittenFun/svelte-vscode#1]
Awesome extension! I'm getting parsing errors in a couple spots:

- When trying to inject structured data into the document head, the parser is looking for a semicolon.
```
{@html `<script type="application/ld+json">${JSON.stringify(structuredData)}</script>`}
```

- Setting variables at the top of an inline scss style block triggers a "Selector is expected" error.
```
<style type="text/scss">
  $dark-gray: #bbb;
</style>
```

**Comment by jamesbirtles** [comment]
heh that first one is fun and a little tricky to fix 100% properly but I can fix this case at least

as for the scss block, you'll need to set up a `svelte.config.js` (relevant svelte issue sveltejs/svelte#1101) to tell the language server how to preprocess it.
e.g.
```js
const sass = require('node-sass');

module.exports = {
    preprocess: {
        style: async ({ content, attributes }) => {
            if (attributes.type !== 'text/scss') {
                return;
            }

            const result = await renderScss({
                data: content,
                sourceMap: 'style.css.map',
                omitSourceMapUrl: true,
            });

            return {
                code: result.css.toString('utf8'),
                map: result.map.toString('utf8'),
            };
        },
    },
};

```

**Comment by morleytatro** [comment]
I was actually able to work out the first situation with the following, which doesn't throw any errors:
```{@html '<script type="application/ld+json">' + JSON.stringify(structuredData) + '</script>'}```

In the second case, I already have preprocessing set up in my Webpack config. I don't believe the error is coming from that since it's triggered irrespective of whether or not the project is running with HMR. Also, I'm not seeing errors with any of my other scss nested blocks. Here's my current preprocess module which is plugged into my Webpack config:
```
const sass = require('node-sass');

module.exports = {
  style: async({ content, attributes }) => {
    if (attributes.type !== 'text/scss') return;

    return new Promise((resolve, reject) => {
      sass.render({
        data: content,
        includePaths: ['routes'],
        sourceMap: true,
        outFile: 'x' // this is necessary, but is ignored
      }, (err, result) => {
        if (err) return reject(err);

        resolve({
          code: result.css.toString(),
          map: result.map.toString()
        });
      });
    });
  }
}
```

I ran into a couple issues when I tried your config:
- renderScss is undefined: sass.render should probably be used there.
- A reference error: something along the lines of "can't reference property css of undefined."

**Comment by jamesbirtles** [comment]
Oops sorry I tweaked the code from my config without testing it.

The language server can't pickup the preprocessor you have set up in webpack, it needs to find in `svelte.config.js`

Based on yours create a `svelte.config.js` file with this:
```js
const sass = require('node-sass');

module.exports = {
    preprocess: {
        style: async ({ content, attributes }) => {
            if (attributes.type !== 'text/scss') return;

            return new Promise((resolve, reject) => {
                sass.render(
                    {
                        data: content,
                        sourceMap: true,
                        outFile: 'x', // this is necessary, but is ignored
                    },
                    (err, result) => {
                        if (err) return reject(err);

                        resolve({
                            code: result.css.toString(),
                            map: result.map.toString(),
                        });
                    },
                );
            });
        },
    },
};

```

**Comment by morleytatro** [comment]
Hmmm... That didn't work. I tried putting it in the root directory and in some other places. Does it need to go somewhere specific?

**Comment by jamesbirtles** [comment]
Root of your project should work, although right now it if errors it doesn't handle it very gracefully. If you go to `View > Output` and then select `Svelte` in the dropdown is there anything logged?

**Comment by jamesbirtles** [comment]
Also if you haven't already you'll need to set [svelte.language-server.runtime](https://github.com/UnwrittenFun/svelte-vscode#sveltelanguage-serverruntime) in your vscode preferences to point to your node binary

**Comment by morleytatro** [comment]
When I go to output, I don't have Svelte in the dropdown at all.

> Also if you haven't already you'll need to set svelte.language-server.runtime in your vscode preferences to point to your node binary

Is this required since the syntax highlighting, etc. are already working?

**Comment by jamesbirtles** [comment]
It's required when using node-sass as its a binary module that needs to match the v8 version of your node install, rather than vscode's

Might look into trying to auto detect this value for reduced friction

**Comment by morleytatro** [comment]
That worked! Well done on the issues. I'm going to close this one.

**Comment by jamesbirtles** [comment]
Awesome 😄

**Comment by goranmandiccrs** [comment]
Hi, @UnwrittenFun ,
 I've added 
`"svelte.language-server.runtime": "file:///C:/Program Files/nodejs/node.exe"`
to my VS code config, and I've added the svelte.config.json to the root of my project (in this case it's the sapper-template) and I'm still getting `Identifier is expectedsvelte(css-syntax-error)` when writing sass in my style blocks. Any ideas on what might be the problem? 
Svelte Output says: Using Svelte v3.1.0 from c:\Users\Goran Mandic\source\my-app\node_modules\svelte\compiler

**Comment by meeroslav** [comment]
> Root of your project should work, although right now it if errors it doesn't handle it very gracefully. If you go to `View > Output` and then select `Svelte` in the dropdown is there anything logged?

For me this helped. What was the issue in my case was that I blindly copied the `svelte.config.js`. @UnwrittenFun has `includedPaths` set to `routes` but in my case it was `src`.

I still needed to provide node path, which is rather unexpected. I would expect this to be automatic.

**Comment by Egnus** [comment]
For those who actually mark the style tags with `lang="scss"`, I have added another condition to the config passed by @UnwrittenFun.

```javascript
const sass = require('node-sass');

module.exports = {
    preprocess: {
        style: async ({ content, attributes }) => {
            if (attributes.type !== 'text/scss' && attributes.lang !== 'scss') return; // lang is now taken into account

            return new Promise((resolve, reject) => {
                sass.render(
                    {
                        data: content,
                        sourceMap: true,
                        outFile: 'x', // this is necessary, but is ignored
                    },
                    (err, result) => {
                        if (err) return reject(err);

                        resolve({
                            code: result.css.toString(),
                            map: result.map.toString(),
                        });
                    },
                );
            });
        },
    },
};
```

**Comment by GottZ** [comment]
i'd probably also add sass support for the other kind of cool kids too.
https://gist.github.com/GottZ/4b1b94dec410aae37c688d2529a80e9a

**Comment by Zerowalker** [comment]
are you still supposed to write this code manually?
Can you make use of svelte-preprocess somehow,
as it looks the same as you have in the webpack.config.js,
and with svelte-preprocess you do like:  `preprocess: require("svelte-preprocess")({})`

**Comment by robertpiosik** [comment]
Hey @UnwrittenFun Would this be ever automatic? Pointing to node executable and creating `svelte.config.js` is inconvenient.

**Comment by jamesbirtles** [comment]
> Hey @UnwrittenFun Would this be ever automatic? Pointing to node executable and creating `svelte.config.js` is inconvenient.

I would like it to be, although I don't have a lot of time atm

**Comment by mdorda** [comment]
Still no success... Am I doing anything wrong?
1. I set `svelte.language-server.runtime` to `/usr/local/bin/node` (Mac)
2. I added `svelte.config.js` to the root of project with [UnwrittenFun content](https://github.com/UnwrittenFun/svelte-vscode/issues/1#issuecomment-386102312) and also with [Egnus content](https://github.com/UnwrittenFun/svelte-vscode/issues/1#issuecomment-495927947)

If I have any error in my SASS code, it does not show anything in a vscode UI. Svelte console contains errors like:

```
(node:56871) UnhandledPromiseRejectionWarning: Error: Invalid CSS after "    h4 {": expected "}", was ".fresh-titletest}"
    at options.error (/...whatever.../index.js:291:26)
(node:56871) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:56871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and the error object I reject in `svelte.config.js` has this structure:

```
{ Error: Invalid CSS after "    h4 {": expected "}", was ".fresh-titletest}"
    at options.error (/...whatever.../index.js:291:26)
  status: 1,
  file: 'stdin',
  line: 2,
  column: 8,
  message:
   'Invalid CSS after "    h4 {": expected "}", was ".fresh-titletest}"',
  formatted:
   'Error: Invalid CSS after "    h4 {": expected "}", was ".fresh-titletest}"\n        on line 2 of stdin\n>>     h4 {.fresh-titletest}\n\n   -------^\n' }
```

So it obviosly run the preprocessor and found the error, but it does not pass the information to vscode UI. Any ideas? Thanks!

**Comment by mdorda** [comment]
I tried to investigate it further, but I am stucked... The style preprocessor is fired [here](https://github.com/UnwrittenFun/svelte-language-server/blob/723310cfaefeb5aff0d4c769e79127eecea96117/src/plugins/SveltePlugin.ts#L159-L172), in `svelte-language-server`. The `makePreprocessor` function is called only from public method `getDiagnostics` of `SveltePlugin` class. An instance of the class is created and registred [here](https://github.com/UnwrittenFun/svelte-language-server/blob/f5d315201f2f1d6a7500c7736ffdd831bb0c7aa7/src/server.ts#L36).

There are no try-catch blocks at all. So it is not suprising it ends with an error. But I have no idea who handles registred instance of the `SveltePlugin`. I would be more than happy for any help.

**Comment by mdorda** [comment]
I've made it work finally. For `less` (but it is same even for `scss`, just different renderer), use the `svelte.config.js` below:

```js
const less = require('less');

module.exports = {
    preprocess: {
        style: async ({ content, attributes, filename }) => {
            if (attributes.lang !== 'less') {
                return;
            }
            try {
                const { css, map, imports } = await less.render(content, {
                    filename,
                    sourceMap: {},
                });

                return { code: css, map, dependencies: imports };
            } catch (e) {
                return e;
            }
        },
    },
};
```
