### ISSUE TITLE
Language specific features not working

### ISSUE THREAD

**Issue by diminutivesloop** [UnwrittenFun/svelte-vscode#100]
Issue Type: <b>Bug</b>

I recently installed this extension but even after configuring the file association for .svelte files nothing appears to have changed. Go to definition doesn't work at all and the syntax highlighting and intellisense pop-overs are identical to what I would get if the file association was set to HTML. In addition the extension is not setting a custom icon for .svelte files.

Extension version: 0.9.3
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (12.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mvolkmann** [comment]
I'm pretty sure the creator of this extension has decided to no longer support it. The last commit was on October 7, 2019. I have submitted issues that have never been addressed.

**Comment by diminutivesloop** [comment]
Well that sucks. Are there any alternatives available yet? I didn't see anything obvious when I searched the extension market.

**Comment by gotofritz** [comment]
Try this https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode
