### ISSUE TITLE
Do you need to disable the default CSS linter for SCSS to work?

### ISSUE THREAD

**Issue by maximedupre** [UnwrittenFun/svelte-vscode#103]
I get CSS errors in my SCSS style tag.

![Screen Shot 2020-03-05 at 9 01 00 AM](https://user-images.githubusercontent.com/5158181/75988633-e14e7000-5ebf-11ea-837f-b14a788f9949.png)

I followed the instructions in the doc, but I think it is incomplete since I have this error...

Cheers!

**Comment by magnus-eriksson** [comment]
Having the same issue. It's only VSCode that complains. It can build it perfectly. 

**What I've tried:**
* Added the full path to node in settings (ran `which node` and copy/paste'd the path).
* Restarted the language server (`ctrl + shift + p` and `Svelte: Restart Language Server`)
* Restarted VSCode

**The style:**
```
<style type="text/scss">
    main {		
        h1 {
	    color: #ff3e00;
        }
    }
</style>
```
**The error:** on the line `h1 {`
```
Colon is expected svelte(css-syntax-error)
```

**Comment by bleucitron** [comment]
Same problem here.
I followed [`svelte-preprocess` instructions](https://github.com/kaisermann/svelte-preprocess#with-svelte-vs-code).

The scss is functional, but i'm still getting errors in VS Code.
<img width="253" alt="Capture d’écran 2020-03-19 à 11 01 26" src="https://user-images.githubusercontent.com/8417814/77055358-061f0900-69d1-11ea-99aa-4f46700f11e2.png">


**`Index.svelte` style**:
```
<style lang="scss">
  $color: orange;
  p {
    color: $color;
  }
</style>
```

**`svelte.config.js`**
```
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
  preprocess: sveltePreprocess(),
};
```

**Comment by NicholasPedroso** [comment]
Same problem here.
Tried everything. but just cant get this to work. This highlight syntax sucks :/

**Comment by aekarahan** [comment]
Same problem.

**Comment by Zequez** [comment]
After going through the code I figured the extension fails silently when `svelte.config.js` is invalid, so be extra sure the file doesn't has any syntax errors. Also make sure the output looks like this:

```
> require("./svelte.config.js")
{
  preprocess: {
    markup: [AsyncFunction: markup],
    script: [AsyncFunction: script],
    style: [AsyncFunction: style]
  }
}
```

Also, as a side note, SASS syntax is not supported, because it's not supported by [vscode-css-languageservice](https://github.com/Microsoft/vscode-css-languageservice/issues/33). I'm not sure how pure `.sass` files do it.

**Comment by holgor** [comment]
Same problem.Try as the instructions.I created a file name `svelte.config.js` like this:
`import { scss } from "@kazzkiq/svelte-preprocess-scss";

module.exports = {
    preprocess: scss(),
    // ...other svelte options
};`
VSCode still shows svelte(css-syntax-error)
