### ISSUE TITLE
Add stylelint support

### ISSUE THREAD

**Issue by SteveALee** [UnwrittenFun/svelte-vscode#105]
I'm using [tailwind CSS](https://tailwindcss.com/) which currently requires disabling VSCode's builtin CSS and [configuring](https://github.com/tailwindcss/discuss/issues/111) of [stylelint](https://stylelint.io/)

The problems occur with the `@tailwind` and `@apply` extensions

However, it appears that this extension calls always VSCodes builtin CSS checking

- `"css.validate": false`, is ignored
- there is no way to get stylint to be called on the .svelte files CSS section

Is there a solution?

**Comment by dhonx** [comment]
> However, it appears that this extension calls always VSCodes builtin CSS checking

Yes... it is, I will try to find the solution when I was free...
