### ISSUE TITLE
Syntax highlighting breaks Bracket Colorizer 2

### ISSUE THREAD

**Issue by marcusnewton** [UnwrittenFun/svelte-vscode#107]
I use https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2 to keep track of bracket usage throughout my js code. I love this extension except that it makes all my brackets gray.

**Comment by dhonx** [comment]
@marcusnewton I think you should use that as a feature request to [bracket-pair-colorizer-2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2)

This extension can't handle that.

**Comment by dhonx** [comment]
BTW The [bracket-pair-colorizer-2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2) is work well on me  🙂
![svelte vscode screenshoot](https://user-images.githubusercontent.com/17797740/78706472-b7b2b980-7941-11ea-8ee2-d65fd6291087.png)

**Comment by marcusnewton** [comment]
Any idea why it might be working for you but not for me?
