### ISSUE TITLE
js single quotes in svelte

### ISSUE THREAD

**Issue by gretadigital** [UnwrittenFun/svelte-vscode#109]
Is there a way to format js with single quotes on save? They revert to double quotes when I format.

**Comment by mvolkmann** [comment]
@jooami I can share a way to do this that does not use this extension. Email me if you're interested. r.mark.volkmann@gmail.com

**Comment by gotofritz** [comment]
@mvolkmann I am also interested... why emailing? Why not just share it here?

**Comment by mvolkmann** [comment]
It’s because I’m writing a book on Svelte and I don’t think I can share sections of it with a large number of people for free. But I’ll email the content to you if you’d like.

---
R. Mark Volkmann
Object Computing, Inc.

**Comment by gotofritz** [comment]
Well I never found out what @mvolkmann's trick was, but in the end I got it working with an annoying workaround:

1. npm i -D prettier@1.19 prettier-plugin-svelte in your project
2. add `"plugins": ["prettier-plugin-svelte"]` into your project's .prettierrc or whatever it's called
3. make sure in your VSCode's settings you have 
```
  "[svelte]": {
    "editor.defaultFormatter": "JamesBirtles.svelte-vscode"
  }
```
4. restart vscode
5. profit

**Comment by dhonx** [comment]
@jooami @gotofritz The trick is simple 🙂
- Create a new `.prettierrc` file on the main root of your project folder
- Paste the following code

```json
{
  "singleQuote": true
}
- restart vscode
```

**Comment by gotofritz** [comment]
🙄 if only...

**Comment by dhonx** [comment]
@gotofritz Is that work?
Also, I think we should use this instead => [svelte.svelte-vscode](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode)

**Comment by gretadigital** [comment]
@dhonx  Thanks, the .prettierrc file is how I was able to get mine working. In that file I also use "svelteSortOrder": "scripts-markup-styles" to keep the markup above the style on save.

@gotofritz The problem with the JamesBirtles formatter for me was that while it fixes the single quotes problem, when you command + / markup to comment it out, it gives you JavaScript // comments instead of

**Comment by gretadigital** [comment]
HTML comments

**Comment by gotofritz** [comment]
I don't experience any of that but have different issues, I think there are too many variables at play and I'll just wait for prettier-plugin-svelte to be compatible with prettier 2

**Comment by dhonx** [comment]
@jooami Why you dont use [svelte.svelte-vscode](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode)

**Comment by gretadigital** [comment]
I do use that, but I still need the prettierrc file for it work right for me. I was just pointing out that in the past when I had tried the James Birtle extension it didn't work right for me, but now with the svelte.svelte-vscode and the .prettierrc file, everything is working the way I want it to.

**Comment by dhonx** [comment]
Ohhh... Please note that you can't put `svelte-vscode` setting on the `.prettierrc` file.
