### ISSUE TITLE
Expected an assignment or function call and instead saw an expression, but it's legal

### ISSUE THREAD

**Issue by frederikhors** [UnwrittenFun/svelte-vscode#115]
Using this:

```svelte
let canRender

$: canRender, console.log('HI')
```

is perfectly fine and it works.

But I get an error:

![image](https://user-images.githubusercontent.com/41120635/79887461-2a6c6c00-83fb-11ea-91dd-4fc5de9df092.png)

```
Expected an assignment or function call and instead saw an expression (eslint, no-unused-expressions)
```

Why?

**Comment by jasonlyu123** [comment]
This is because the `canRender` expression causing eslint to report linting error.
