### ISSUE TITLE
Support spaces between brackets with keyed #each

### ISSUE THREAD

**Issue by cklmercer** [UnwrittenFun/svelte-vscode#12]
The svelte compiler does not appear to enforce white-space/no-white-space between brackets.

For example the following are both valid:
```
{ #each $alerts as alert }
{#each $alerts as alert}
```

These also both work, no problem, with this extension. The issue comes arises whenever you use a keyed `#each` statement with v2 syntax.

The following breaks syntax highlighting:
```
{ #each $alerts as alert (alert.id) }
```

**Comment by jamesbirtles** [comment]
Fixed in 0.3.2

Thanks!
