### ISSUE TITLE
Emmet autocomplete doesn't always trigger

### ISSUE THREAD

**Issue by jamesbirtles** [UnwrittenFun/svelte-vscode#13]
From https://github.com/UnwrittenFun/svelte-vscode/issues/2#issuecomment-387283527

When going any more complicated that just `div` for example, the autocomplete box doesn't always show up, or shows up and then disappears every other keystroke.

Example where it toggles every keystroke
```
div.myclass
```

Example where it just flat out doesn't show:
```
ul>li*3
```

You can still trigger it manually however with ctrl+space

**Comment by silentworks** [comment]
Yeah I just hit this very issue. Good to see you already found it.

**Comment by sergeche** [comment]
In your preferences, add the following option:

```json
"emmet.includeLanguages": { "svelte": "html" }
```

It will enabled automatic completions for Svelte HTML. Although won’t work in embedded syntaxes like CSS/SCSS, seems like a bug in detecting activation context in Emmet plugin

**Comment by jamesbirtles** [comment]
finally figured this one out, fix incoming
