### ISSUE TITLE
Add Stylus support as SASS/LESS

### ISSUE THREAD

**Issue by stalkerg** [UnwrittenFun/svelte-vscode#16]
Subj.

**Comment by arxpoetica** [comment]
I would say this slightly differently. Add language support in general. This could be added using the `type` attributes on both `<script>` and `<style>` tags:

Examples:

```
<style type="text/SCSS">
  .wowza {
    .nested { ... }
  }
  // <- this was commented with two slashes because the language support for the style tag read it as scss!
</style>
```

or

```
<script type="text/TypeScript">...</script>
```

Etc.

For the sake of ease of use, *maybe* the language support namespaces should ignore case.


```
'text/PostCSS'.toLowerCase() === 'text/postcss'.toLowerCase()
```

Links:

https://code.visualstudio.com/docs/languages/html
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#attr-type
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type

**Comment by arxpoetica** [comment]
I haven't had a chance to delve into it, but supposedly this plugin does something along these lines? https://github.com/vuejs/vetur In general, this is probably a good reference. Relevant ticket: https://github.com/Microsoft/vscode/issues/17460

**Comment by jamesbirtles** [comment]
The plugin currently already supports the following for syntax highlighting:
```html
<style type="text/scss"></style>
<style type="text/sass"></style>
<style type="text/less"></style>
<style type="text/stylus"></style>
<style type="text/postcss"></style>
<script type="text/typescript"></script>
<script type="text/coffee"></script>
```

These are defined like below for each language
https://github.com/UnwrittenFun/svelte-vscode/blob/a40e28ce26c7e7ef395190d53f25e8ae4c5725b2/syntaxes/svelte.tmLanguage.json#L8

Which I did actually tweak from vetur

I was assuming support for stylus in this issue refers to adding language server support for completions, highlighting etc.

**Comment by arxpoetica** [comment]
Hey! That worked great! What'dya know! (Should have actually tested it before I went snipe hunting on GitHub. 😂)

**Comment by arxpoetica** [comment]
Question though, if linting tools work in straight up `*.scss` files, for example, how do we get them to work in the `<style type="text/scss">...</style>` tags? Or is that not this plugin's responsibility?

**Comment by kaisermann** [comment]
@arxpoetica For now I'm using 'stylelint-processor-arbitrary-tags' for that: 


```js
// .stylelintrc.js
module.exports = {
  extends: 'stylelint-config-standard',
  plugins: ['stylelint-scss'],
  processors: [
    [
      '@mapbox/stylelint-processor-arbitrary-tags',
      {
        fileFilterRegex: [/\.(svelte|html)$/],
      },
    ],
  ],
  rules: {
 	...
  },
}
```

**Comment by antony** [comment]
Very pleased to see this feature, as I've been struggling with it!

Would it be possible to alias the Vue style (and the method supported by the svelte sass plugin) of doing:

```
<style lang="scss">
</style>
```

too?

**Comment by jamesbirtles** [comment]
@antony that will be supported in the next release 😄

**Comment by jamesbirtles** [comment]
I did some searching for a stylus language server but it doesn't appear there is one. To add proper support we'll likely need to extract some of the smarts from this plugin https://github.com/d4rkr00t/language-stylus

Syntax highlighting should already be supported via `type="text/stylus"` or `lang="stylus"`. Let me know if not!

**Comment by antony** [comment]
Interesting - I'll double check this now.

**Comment by antony** [comment]
Sorry, just realised this relates to stylus not sass :) I'm getting some issues with sass support but I'll raise this in another ticket to keep this one stylus focussed.

**Comment by s0kil** [comment]
SCSS support would be great!

**Comment by arxpoetica** [comment]
@DanielSokil SCSS support already exists. Just add the following to your style tag:

```
<style type="text/scss">
...
</style>
```

Works out of the box.

**Comment by s0kil** [comment]
When using SCSS, Svelte VScode extension reports it as bad syntax with errors, trying to read it as CSS

**Comment by arxpoetica** [comment]
@DanielSokil you might be right; that seems to be a seperate bug.
