### ISSUE TITLE
Use eslint for JS instead TypeScript

### ISSUE THREAD

**Issue by stalkerg** [UnwrittenFun/svelte-vscode#18]
I use a special plugin for "rollup" for change root of modules and same behavior for eslint but VS Svelte plugin show error for any import because not understand that.
Is it possible disable current validation and enable eslint?

**Comment by arxpoetica** [comment]
I'm going to bump this. Should we be using `type="..."` in our script tags as well? I would think the default should be JS, and upgrades to other compilers like TS can either be specified in settings or in `type="..."`???

**Comment by jamesbirtles** [comment]
It does default to JS, however I have the settings cranked a bit too high where its doing typescript level of checking on plain JS. I need to sit down and figure out how to wrangle TypeScript to my needs.

Just an fyi that you can disable this for now with `"svelte.plugin.typescript.diagnostics.enable": false`
in your vscode settings

**Comment by arxpoetica** [comment]
okay, thanks!

**Comment by jamesbirtles** [comment]
We're now no longer reporting semantic errors when in javascript mode so it only errors on syntactic errors. I think this addresses the original request
