### ISSUE TITLE
Lint error for components using SCSS

### ISSUE THREAD

**Issue by kazzkiq** [UnwrittenFun/svelte-vscode#19]
When using components with `<style type="text/scss">` and calling variables, I keep getting this lint error even though it still compiles the project successfully.

Code example:

```html
<h1>Hello, world?</h1>

<style type="text/scss">
  @import './variables';
  h1 {
    color: $color-gold;
  }
</style>
```

This is the error I get: 

```
[svelte] Unexpected input
Color of an element's text
```

![2018-06-14 13_23_42](https://user-images.githubusercontent.com/1953194/41425159-4927b4c8-6fd6-11e8-9d5e-f33150e630c4.gif)

**Comment by jamesbirtles** [comment]
You'll need to set up a `svelte.config.js` file in the root of your project to tell the plugin how to deal with your css.

You can find an example here https://github.com/UnwrittenFun/svelte-vscode/issues/1#issuecomment-386102312

You'll also need to set the `svelte.language-server.runtime` preference in vscode to point to your nodejs executable

**Comment by jamesbirtles** [comment]
I've created #20 to add documentation for this behaviour

**Comment by kazzkiq** [comment]
Solved, thanks!

**Comment by kylecordes** [comment]
This appears to work (and is much appreciated). And I can see why it is beneficial to be able to run the project local node-sass, and why that requires this extra configuration to go find the right Node executable. But it's also pretty far afield from developer ergonomic expectations for VSCode - it would probably be better if it "just worked" however other Sass-aware add-ons for VSCode work, even if that means potentially a Sass version mismatch :-(
