### ISSUE TITLE
Does Emmet still work?

### ISSUE THREAD

**Issue by arxpoetica** [UnwrittenFun/svelte-vscode#2]
This is awesome, but emmet (and normal HTML autocompletion, etc.) seems to have stopped working for me...I know so little about VS Code extensions to know how to help...

**Comment by jamesbirtles** [comment]
Yeah unfortunately it's something that needs to be implemented manually.

Luckily it looks like it might be relatively easy to add in using this https://github.com/Microsoft/vscode-emmet-helper

**Comment by arxpoetica** [comment]
Cool. So am I understanding you to say this can be done by your plugin? Or are you saying I need to implement this somehow? #confused

**Comment by jamesbirtles** [comment]
I'll be adding it, sorry for the confusion :)

In the mean time you could possibly try adding this to your vscode preferences:
```json
"emmet.showExpandedAbbreviation": "always",
"emmet.includeLanguages": { "svelte": "html" }
```
Not tested it but Microsoft/vscode#29532 suggests it might work

**Comment by jamesbirtles** [comment]
Released in v0.2.0

**Comment by arxpoetica** [comment]
This needs to be reopened. Emmet abbreviations have started working again, but somehow single/short abbreviations are the only thing working.

This works:

![image](https://user-images.githubusercontent.com/111424/39733112-41a4fa9c-529b-11e8-90d3-889182272bc6.png)

This does not:

![image](https://user-images.githubusercontent.com/111424/39738551-035b0766-52b6-11e8-949d-9199337af124.png)

I had to change the language mode from Svelte to HTML to get that last one to work.

Here's a cheat sheet of different possibilities, for reference: https://docs.emmet.io/cheat-sheet/

**Comment by jamesbirtles** [comment]
hmm, I can get that second one to work, however it only shows up if I manually trigger autocompletion with ctrl+space. Also curiously when it does decide to open the auto complete box automatically, it disappears every other keystroke. I'll open a new issue for this
