### ISSUE TITLE
Disable default JS and CSS validation

### ISSUE THREAD

**Issue by kaisermann** [UnwrittenFun/svelte-vscode#21]
I've tried everything I could thought of to disable this kind of `js` validation but can't seem to disable it. Is this somehow tied to this plugin?

![image](https://user-images.githubusercontent.com/12702016/41860166-4b8c7a90-7874-11e8-80a4-5a84fb746029.png)

I've already disabled all kind of validations on my workspace settings: 

![image](https://user-images.githubusercontent.com/12702016/41860207-6cb722ec-7874-11e8-9bba-63c28be1b4fe.png)

**Comment by kaisermann** [comment]
I think I've managed to find why is this happening: https://github.com/UnwrittenFun/svelte-language-server/blob/master/src/plugins/CSSPlugin.ts#L54 

This line is forcing the validation of the whole document. If I remove it, those errors disappear (both the css and js ones)

**Comment by jamesbirtles** [comment]
Added in 0.5.0

**Comment by jackyef** [comment]
@UnwrittenFun I am currently having `File '/path/to/file.html' is not a module` error when using this extension. I can not seem to find how to turn it off. I am using version 0.6.1.
