### ISSUE TITLE
Improve HTML formatting

### ISSUE THREAD

**Issue by kylecordes** [UnwrittenFun/svelte-vscode#22]
(Feature request)

Currently the plug-in can auto-format (using Prettier) the JavaScript code portion of the component ( as well as the CSS). But many Svelte components are comprised quite substantially of HTML, and currently the plug-in takes over auto-formatting of the entire file but does not format the HTML.

Thus the feature request:

* auto-format the HTML
* Respecting the Svelte syntax
* Ideally, produce consistent and reasonable output regardless of how the input was formatted, so that the output ends up formatted the same way regardless of details of how a particular human typed the input the first time.

**Comment by jamesbirtles** [comment]
Not sure where prettier are with their HTML support. Choices are
- Wait for prettier to finish adding html support
- Use another formatter for html (preferably one that handles svelte's syntax well)
- Write our own

**Comment by jamesbirtles** [comment]
Looks like the html language service provides a formatter. It's not 100% perfect for svelte but I am going to add it (it can easily be disabled).

I'm going to keep this issue open to improve the formatting later

**Comment by kylecordes** [comment]
The built-in formatter certainly seems better than no formatter.  of course something that really understands the Svelte syntax would be much better... this is a corner of software development I have never touched though, don't have any sense of whether that is a modest sized idea or a very large one.

**Comment by jamesbirtles** [comment]
Ended up writing a [plugin for prettier](https://github.com/UnwrittenFun/prettier-plugin-svelte) that properly formats svelte files. I'll be testing it out over the next few days to try and iron out any immediate issues before I add it in here

**Comment by zzolo** [comment]
+1 on this issue.  Not sure what the best/easiest way to go is, but would love to see some more specific syntax formatting for the HTML in Svelte.

Great plugin, btw.

**Comment by dmitry-kurmanov** [comment]
Prettier html format will be cool. Also I think that it would be great if we will have an option `disableHtmlFormat` in the settings. Thank you for the plugin.

in vscode we have `"html.format.enable": false` may be it is right way to disable html formatting for the `svelte-vscode`

**Comment by jamesbirtles** [comment]
You can use `"svelte.plugin.html.format.enable": false`

**Comment by dmitry-kurmanov** [comment]
@UnwrittenFun works like a charm thank you! I did not guess to look for "svelte" in the settings.

**Comment by jamesbirtles** [comment]
[prettier-plugin-svelte](https://github.com/UnwrittenFun/prettier-plugin-svelte) is now used for formatting
