### ISSUE TITLE
Comment shortcut in html and css prepends line with double slashes.

### ISSUE THREAD

**Issue by morleytatro** [UnwrittenFun/svelte-vscode#3]
When I use the comment shortcut (command + /), inside html and style blocks, it simply prepends the lines with //, instead of surrounding them with  and /* */ respectively.

**Comment by jamesbirtles** [comment]
I'll have to investigate how vscode does this properly in html files

**Comment by jamesbirtles** [comment]
Turns out it was very simple

**Comment by jamesbirtles** [comment]
Released in v0.3.0
