### ISSUE TITLE
Add support for PostCSS

### ISSUE THREAD

**Issue by clitetailor** [UnwrittenFun/svelte-vscode#30]
I'm using VSCode with `postcss-sugarss-language` already installed. PostCSS plugin works fine on files with .css extensions. It seems like `svelte-vscode` doesn't fallback to .css files highlight and format plugins. Can you support this?

![image](https://user-images.githubusercontent.com/16368559/49871125-f74dbc00-fe47-11e8-97c0-f0c17ce8706d.png)

**Comment by jamesbirtles** [comment]
try adding lang="postcss" on your style tags, it should at least fix the highlighting

**Comment by adonaicandido** [comment]
![image](https://user-images.githubusercontent.com/9721798/70085443-00064780-15ef-11ea-92c5-aa3032a3e4bb.png)
It doesn't.
