### ISSUE TITLE
Add setting to resolve path aliases.

### ISSUE THREAD

**Issue by PaulMaly** [UnwrittenFun/svelte-vscode#31]
Hi! Thanks for this excellent plugin!

Can we somehow add an ability to specify path aliases for imports?

**// rollup.config.js**
```javascript
import importResolver from 'rollup-plugin-import-resolver';
...
export default {
  ...
  importResolver({ 
    extensions: ['.js', '.html', '.svelte'],
    alias: { '~': './src' },
  }),
  ...
};
```
In components: 

```javascript
import Modal from '~/components/Modal';
```

Right now this config produce warnings like "Cannot find module '~/components/Modal'".

Thanks!

**Comment by jamesbirtles** [comment]
I believe you may be able to this with a jsconfig.json. See https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases

Let me know if it works 😄

**Comment by jamesbirtles** [comment]
Closing this as I've not heard back, feel free to reopen if my proposed solution didn't work
