### ISSUE TITLE
Setting "editor.tabSize" is ignored

### ISSUE THREAD

**Issue by AlexanderShushunov** [UnwrittenFun/svelte-vscode#32]
I have setting `"editor.tabSize": 4`. But "format document" command change indents to 2 spaces.
It happens in Svelte-files only.

**Comment by jamesbirtles** [comment]
Prettier is used to format the code so you should be able to configure prettier to use 4 spaces for now. See https://prettier.io/docs/en/configuration.html

Let me know if that works, and I'll look at making it respect the editor settings by default

**Comment by kuechlerm** [comment]
Using a prettier config file works, thank you.

**Comment by parkerqueen** [comment]
@UnwrittenFun I've Prettier extension installed, with the following manual setting:
`"prettier.tabWidth": 4`

But svelte formatting isn't respecting that. Do I explicitly need a prettier config file or should the VSCode Setting work as well?

**Comment by jamesbirtles** [comment]
You currently specifically need a prettier config file

**Comment by ricardomatias** [comment]
~~It's not working with a prettier config file. I assume I can just add to the top level directory and that I don't need to install anything prettier related that doesn't come with this plugin.~~

Edit:
Actually it works, but you need to reload visual studio code after adding the the `.prettierrc` file.

**Comment by otherdave** [comment]
To piggyback on @ricardomatias last comment - it looks like you need to restart VS Code after _editing_ the `.prettierrc` file, not just adding it. If I have a tabwidth of 2 and restart, it formats correctly. If I change it to 4, the reformat doesn't do anything. I have to restart VS Code then re-run the reformat. Then it'll change to 4.
