### ISSUE TITLE
Problem "Unrecognized option 'preprocess'(undefined)"

### ISSUE THREAD

**Issue by james-bay** [UnwrittenFun/svelte-vscode#33]
I started learning svelte. I installed the template from the svelte repository (https://github.com/sveltejs/template/tree/v3)
```
degit sveltejs/template svelte-app#v3
cd svelte-app
npm install
```
Only the Svelte plugin is installed in vscode and with it vscode displays an error in the .html and .svelte files: "Unrecognized option 'preprocess' (undefined)" on the first tag.
![screenshot_20190225_114808](https://user-images.githubusercontent.com/6966475/53324984-45287b00-38f3-11e9-8ce6-9e0c1855cf1d.png)

**Comment by dalisoft** [comment]
@UnwrittenFun Hello and thanks for VSCode plug-in. But it on my VSCode same issue as @james-bay's issue.

vscode-svelte: 0.7.0
vscode: 1.33.1
os: macOs high sierra
