### ISSUE TITLE
Editor errors while following Svelte 3 tutorial

### ISSUE THREAD

**Issue by Cammisuli** [UnwrittenFun/svelte-vscode#36]
When following the tutorial for Svelte 3, particularly the reactive section with `$: double = count * 2`; VSCode shows an error saying that `double` is not found.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/4332460/56622587-b4260580-65fe-11e9-9f20-65a5d5089a56.png">

I'm not sure if I'm missing any particular dependency or not. But I just started the project with `npx degit svelte/svelte-template my-svelte-project`.

If more information is needed, just let me know.

**Comment by jamesbirtles** [comment]
It doesn't look like doubled is declared in that script

**Comment by Cammisuli** [comment]
You’re absolutely right, it can be fixed by doing `let double` before. But I was following the tutorial here:
https://svelte.dev/tutorial/reactive-declarations

I thought this extension should support that syntax shown in the tutorial.

**Comment by jamesbirtles** [comment]
This is now no longer flagged as an error in v0.8.0 however will still be flagged if you're using typescript
