### ISSUE TITLE
Infinitely indenting block-comments

### ISSUE THREAD

**Issue by tlgreg** [UnwrittenFun/svelte-vscode#37]
If I use the extension as the formatter for `svelte` files any block-comment `<script>` or `<style>` gets constantly pushed except for its first line.

<details>
<summary>Demo (gif)</summary>

![indent](http://g.recordit.co/tHY5QzGPls.gif)

</details>

All I'm hitting here is save, while "format on save" is on.

This is in vscode-insiders 1.34.0

Not an issue at other places where css/js is inside tags (eg.: `html`, `vue`).

**Comment by jamesbirtles** [comment]
funky, I will be replacing the current formatting with prettier soon so should be resolved then

**Comment by jamesbirtles** [comment]
should be fixed in 0.8.0

**Comment by tlgreg** [comment]
I can confirm, it did fix the issue. Thanks and generally for the extension too.
