### ISSUE TITLE
import statement throws a  "Module has no default export" error

### ISSUE THREAD

**Issue by iepsen** [UnwrittenFun/svelte-vscode#38]
Following the example https://svelte.dev/examples#nested-components, I got a "Module has no default export" error:

<img width="830" alt="Screenshot 2019-05-04 at 16 28 28" src="https://user-images.githubusercontent.com/228328/57180545-d1be5f00-6e89-11e9-8b7d-5325a336e4cd.png">

**Comment by jamesbirtles** [comment]
This means the its picking up svelte v2. Do you have v3 installed locally as it should pick up your locally installed version. Will be releasing an update to default to v3 soon.

**Comment by ArtemKolichenkov** [comment]
I'm having the same issue (+#35) and I tried all kinds of things (reload, disabling, reinstalling, etc.). 
Not using TS. Doing basic stuff straight from docs.

**Comment by esbeto** [comment]
How can we help debug why it's not picking up version 3? It seems that a lot of people are having the same issue.

**Comment by jamesbirtles** [comment]
Latest version (0.8.0) should default to svelte v3, let me know if that helps with this

**Comment by ArtemKolichenkov** [comment]
@UnwrittenFun wow, works like a charm after re-installing, thanks! 🙂

**Comment by iepsen** [comment]
Thank you @UnwrittenFun! 👍 😄

**Comment by numfin** [comment]
lang="typescript" has the same problem 
![image](https://user-images.githubusercontent.com/8134947/62804644-94a3e180-baf6-11e9-824d-dc6ecb061eda.png)
