### ISSUE TITLE
Auto removes event modifiers on save

### ISSUE THREAD

**Issue by mickeyvip** [UnwrittenFun/svelte-vscode#40]
When saving a file, the auto formatting removes event modifiers:

```javascript
<form on:submit|preventDefaut={onSubmit}></form>
```
after save becomes:
```javascript
<form on:submit={onSubmit}></form>
```

Svelte - v3.2.1
svelte-vscode - v0.8.0

Thank you

**Comment by juanmait** [comment]
I'm noticing the same issue when I hit the auto formatting key shortcut on mac `cmd+shift+f`, I had to disable formatting: `"svelte.plugin.svelte.format.enable": false`. But now nothing gets formatted. Another option is to map `.svelte` files to HTML.. but that's worst. I'm pretty sure that has something to do with the new support for `prettier-plugin-svelte`. I installed the plugin but the same happens.

**Comment by mickeyvip** [comment]
Also `.html` files are automatically treated as `svelter` and when auto-formatting them the `script` tag is place above the `html`:

```html
<!DOCTYPE html />
<html lang="en">
  <head>
    <meta charset="utf8" />
    <meta name="viewport" content="width=device-width" />

    <title>Svelte app</title>

    <link rel="stylesheet" href="global.css" />
    <link rel="stylesheet" href="bundle.css" />
  </head>

  <body>
    <script src="bundle.js"></script>
  </body>
</html>
```

becomes:

```html
<script src="bundle.js"></script>

<!DOCTYPE html />
<html lang="en">
  <head>
    <meta charset="utf8" />
    <meta name="viewport" content="width=device-width" />

    <title>Svelte app</title>

    <link rel="stylesheet" href="global.css" />
    <link rel="stylesheet" href="bundle.css" />
  </head>

  <body></body>
</html>
```

this makes the app fail.
