### ISSUE TITLE
Output panel keeps popping up

### ISSUE THREAD

**Issue by jarrodldavis** [UnwrittenFun/svelte-vscode#41]
Is there a reason why the extension keeps opening up the Output panel? It's really annoying to be in the middle of typing code in a template and the Output panel keeps going wild.

**Comment by jamesbirtles** [comment]
VS Code seems to do this automatically, not entirely sure of how it decides when to show it. Are there any errors in the output, or is it just logging? I'll see if I can figure out if I can disable it later

**Comment by ArtemKolichenkov** [comment]
This might be irrelevant, but @jarrodldavis are you using VSCode debug mode?

I had (still have actually) similar issue with Flutter/Dart, keeps opening Output panel randomly, haven't found a way to deal with it yet.

But my point is that it might be some VSCode issue unrelated to extension. For me it's ok though, but maybe because I don't use debug mode for JS (assuming your issue is related to it) 🤔

**Comment by tlgreg** [comment]
It pops up here too but it happens on an error.
The error seems to be trigger by the extension trying to run code completion on whitespace when I hit space.
Actual error:
```
  Message: Request textDocument/completion failed with message: Debug Failure. Illegal value: " "
  Code: -32603 
```

**Comment by jarrodldavis** [comment]
@ArtemKolichenkov the issue occurs even when I'm not debugging

@tlgreg Yeah, it's popping up when an error occurs, typically because it can't format the document (since I'm in the middle of typing) or it fails to get completions.

**Comment by juanmait** [comment]
I'm experiencing this too. In my case, it opens when I start typing and a validation error occurs, for example typing an import statement with one space after, like `import `. It shows the same output described by @tlgreg 

```
[Error - 2:15:54 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Debug Failure. Illegal value: " "
  Code: -32603
```

Apparently, there is no way to disable this in vs code as seems to be a responsibility of every extension. If vscode opens the output panel when some `Error` is logged by the extension, maybe the error can be changed to be a warning instead?

**Comment by jamesbirtles** [comment]
Looks like theres an option I can set to disable this panel popping up on error. Will push a fix today
