### ISSUE TITLE
Feature: Debugger for Chrome

### ISSUE THREAD

**Issue by Ragnoroct** [UnwrittenFun/svelte-vscode#42]
How hard would it be to allow breakpoints to be set in .svelte files and debugged/hit using Debugger for Chrome?

If you try to set a breakpoint inside a <script></script> tag nothing will happen.

**Comment by kaisermann** [comment]
A simple (but not ideal) way is to set the vscode setting `debug.allowBreakpointsEverywhere` to `true`:

```
/** Allow to assign breakpoints to svelte templates */
"debug.allowBreakpointsEverywhere": true,
```

**Comment by Ragnoroct** [comment]
That works perfectly. I just needed to tweak my vscode launch config.

```javascript
{
    "type": "chrome",
    "request": "launch",
    "name": "Launch Chrome",
    "url": "http://localhost:3000",
    "sourceMaps": true,
    "sourceMapPathOverrides": {
        "webpack:///*": "${workspaceRoot}/src/client/*"
    },
    "skipFiles": [
        "<node_internals>/**",
    ]
}
```
