### ISSUE TITLE
Does not highlight errors when editing (typescript)

### ISSUE THREAD

**Issue by fourteenmeister** [UnwrittenFun/svelte-vscode#43]
Why not highlight errors when editing? Shows errors only in the console after running npm run dev.

<details>
  <summary>Screenshot</summary>

  ![Picture](https://user-images.githubusercontent.com/3837141/57756622-5451e480-76fc-11e9-8dbc-60981bbd6428.png "Picture")

</details>

<details>
<summary>svelte.config.js</summary>

```javascript
const { preprocess } = require("@pyoner/svelte-ts-preprocess")

module.exports = {
  preprocess: preprocess()
}
```
</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "svelte-ts-app",
  "version": "1.0.0",
  "devDependencies": {
    "@pyoner/svelte-ts-preprocess": "0.0.2",
    "@pyoner/svelte-types": "^3.1.0-1",
    "npm-run-all": "^4.1.5",
    "rollup": "^1.12.0",
    "rollup-plugin-commonjs": "^9.3.4",
    "rollup-plugin-node-resolve": "^4.2.4",
    "rollup-plugin-svelte": "^5.0.3",
    "rollup-plugin-terser": "^4.0.4",
    "rollup-plugin-typescript2": "^0.21.0",
    "sirv-cli": "^0.4.2",
    "svelte": "3.3.0",
    "typescript": "^3.4.5"
  },
  "scripts": {
    "build": "rollup -c",
    "autobuild": "rollup -c -w",
    "dev": "run-p start:dev autobuild",
    "start": "sirv public",
    "start:dev": "sirv public --dev"
  }
}
```
</details>

**Comment by jamesbirtles** [comment]
it doesn't currently support `lang="ts"` it has to be either `lang="typescript"` or `type="text/typescript"`

this will be fixed in the next version

**Comment by fourteenmeister** [comment]
> it doesn't currently support `lang="ts"` it has to be either `lang="typescript"` or `type="text/typescript"`

strange, changed `lang="typescript"` - nothing has changed

**Comment by jamesbirtles** [comment]
I've added some docs on setting up typescript, let me know if this helps
https://github.com/UnwrittenFun/svelte-vscode/blob/master/docs/preprocessors/typescript.md
