### ISSUE TITLE
Add support for Pug

### ISSUE THREAD

**Issue by zeromanser** [UnwrittenFun/svelte-vscode#46]
Add pug highlight fo example for this kind of construction.
`<template lang="pug">
.wrapper
	h1.wrapper__heading Hello {name}
</template>`

**Comment by kaisermann** [comment]
For now, try `type="text/pug"`

![image](https://user-images.githubusercontent.com/12702016/58338620-747d5400-7e1e-11e9-86c3-f492d2f2098e.png)

**Comment by zeromanser** [comment]
> type="text/pug"
its strange but seems doesnt work
![image](https://user-images.githubusercontent.com/8243529/58339594-998bba00-7e52-11e9-89ad-eadc12eb1d6a.png)

**Comment by robertpiosik** [comment]
Hey 👋 Is there any update on this issue?

**Comment by taviks** [comment]
`type=text/pug` does not work for me, either.

It's not really a fix, but reading [this article](https://blog.alphaman.me/make-vscode-know-svelte-cjw2la7o00003e2s1pecsknqe) gave me the idea to do this: 

```
// in vscode settings

"files.associations": {
    "*.svelte": "vue"
},
```

Now vscode essentially treats my Svelte components like Vue components. Note that this likely requires that your vscode be set up with Vue support (mine already was).

**Comment by Maxximus007** [comment]
@yet-another-dev You've probably Vetur running, so your solution kinda works. But it defeats the purpose of the svelte-vscode plugin.

About the matter, I had the issue that the plugin removes the LF between the tags and makes it all one line.

Had to disable `svelte.plugin.svelte.format.enable`  to get things going. Perhaps create a more fine-grained option?
