### ISSUE TITLE
Extention 'Prettier - Code Formatter' cannot format 'path/to/file.svelte'

### ISSUE THREAD

**Issue by sndrs** [UnwrittenFun/svelte-vscode#48]
I've installed `v0.9.1`, and set `language-server.runtime` too.

I cannot get any svelte file to format though, I always get a `Extention 'Prettier - Code Formatter' cannot format 'path/to/file.svelte'` in the code status bar.

the console for `svelte` only contains:

```
Using Svelte v3.4.3 from /Users/alexsanders/Dev/my-app/node_modules/svelte/compiler
Using Svelte v3.4.3 from /Users/alexsanders/Dev/my-app/node_modules/svelte/compiler
Using Svelte v3.4.3 from /Users/alexsanders/Dev/my-app/node_modules/svelte/compiler
Using Svelte v3.4.3 from /Users/alexsanders/Dev/my-app/node_modules/svelte/compiler
Using Svelte v3.4.3 from /Users/alexsanders/Dev/my-app/node_modules/svelte/compiler
Using Svelte v3.4.3 from /Users/alexsanders/Dev/my-app/node_modules/svelte/compiler
Using Svelte v3.4.3 from /Users/alexsanders/Dev/my-app/node_modules/svelte/compiler
```

so looks ok. am i doing something stupid?

**Comment by sndrs** [comment]
i am! sorrty :)

**Comment by starchturrets** [comment]
I'm facing the same issue, what were you doing wrong? How did you fix it?

**Comment by starchturrets** [comment]
Nvm, I figured it out. Make sure to set the default formatter for svelte files as this extension, not prettier.
