### ISSUE TITLE
Does not highlight consistently between two files with the same content:

### ISSUE THREAD

**Issue by mikemaccana** [UnwrittenFun/svelte-vscode#49]
I have a `.svelte` file that throws up odd errors using this syntax highlighter:

![image](https://user-images.githubusercontent.com/172594/58631743-65454d00-82db-11e9-803d-8e1a873f5d00.png)

For example:

![image](https://user-images.githubusercontent.com/172594/58631757-72fad280-82db-11e9-8095-a8d1daf72d2b.png)

**This is a valid Svelte file that compiles, taken from the Svelte tutorial  It should not have any errors,**

However if I copy the file to a different name, Svelte no longer complains:

![image](https://user-images.githubusercontent.com/172594/58631821-9de52680-82db-11e9-9cfc-2a28237d9976.png)

**Comment by mikemaccana** [comment]
Pressing "ctrl+shift+p" > reload window, will fix the bad highlighting. Any tips to debug it next time it happens?

**Comment by jamesbirtles** [comment]
I think the server was getting a little overloaded, we have added some debouncing to the calls so this may help with this.

Please reopen if still an issue with the latest version.
