### ISSUE TITLE
JavaScript Formatting

### ISSUE THREAD

**Issue by stevesob** [UnwrittenFun/svelte-vscode#52]
I can't seem to get the <script> section to format correctly,

I have prettier installed and set for no semicolons and printer width of 180, however semicolons are always added and lines wrap at 80 characters.

I know it's my setup but any help would be appreciated.

Also, html is wrapping at 80 columns.

**Comment by jamesbirtles** [comment]
how are you configuring your prettier?

**Comment by stevesob** [comment]
In .vscode/settings.json 

"prettier.semi": false,
"prettier.printWidth": 180,

**Comment by jamesbirtles** [comment]
ah, that will only set it for the vscode prettier extension which this bypasses. you'll need to set up your config following https://prettier.io/docs/en/configuration.html

**Comment by stevesob** [comment]
You made my day! That got it working, but I had to uninstall prettier and install prettier-vscode.

I hope this helps others with the same problems.

**Comment by jaybeemind** [comment]
> ah, that will only set it for the vscode prettier extension which this bypasses. you'll need to set up your config following https://prettier.io/docs/en/configuration.html

Hey man, how did you make it work? I created a **.prettierrc** file like it suggested in @stevesob 's link, but it did not override svelte's formatting.

**Comment by jaybeemind** [comment]
Nevermind, I made it work by adding a **.prettierrc** and installing prettier-vscode too. The problem was caused by another vscode plugin, **beutify**. I disabled it, and it worked!
