### ISSUE TITLE
[Feature Request] 'go to definition' enhancement

### ISSUE THREAD

**Issue by wangchou** [UnwrittenFun/svelte-vscode#53]
I found `go to defintion` is not working in following cases

### 1. store variable with auto-subscriptions
when press F12 on **$count**, it won't go to definition
```js
import { count } from './store.js'

$: double = $count * 2
```

### 2. variables & functions in html section
when press F12 on **{count}** or **{handleClick}**, it won't go to definition.
![スクリーンショット 0001-06-20 13 24 26](https://user-images.githubusercontent.com/32716/59822913-d1f1bb80-935e-11e9-99ca-0015c579995a.jpg)

(ps: go to definition works on html files, ex: `<button onclick="handleClick">`)

### 3. svelte component tag
when press F12 on **Nested**, it won't open Nested.svelte file.
```jsx
<script>
	import Nested from './Nested.svelte';
</script>

<Nested answer={42}/>
```
(ps: I read an [article](https://github.com/Microsoft/vscode/issues/27022) said React Components support this)

I just moved from vim to vscode for one week, because this extension is the only way I found to do correct syntax highlight for Svelte. 😄 But the above experience made me think vscode didn't do `go to definition` correctly at all, so I created a [stupid extension](https://github.com/wangchou/vscode-go-to-export/blob/master/extension.js#L14) for `go to definition` by global search... 😭 

I guess supporting it via `vscode language server?` will be better approach.

**Comment by juanmait** [comment]
Hey @wangchou ! Is "go to file/module" working for you? Or is another improvement to be done? It isn't working for me :( Thanks!

**Comment by moshfeu** [comment]
@juanmait it's not working for me even it's on the [features list](https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode#features)

**Comment by juanmait** [comment]
@moshfeu as far I could investigate, this seems to be some how out of scope for svelte-vscode, and is more on the vscode side. See this issue: https://github.com/microsoft/vscode/issues/26338. Apparently they're on the way to support intellisense in regular script tags, specifically on tags like `<script type=module>` (check this one: https://github.com/microsoft/vscode/issues/29315), which is very close to become "more popular" and is already supported in browsers. This would be the preferred solution as it would mean to have a sort of "native" support for intellisense in vscode. That's my guess though. We'll see..

**Comment by chazshi** [comment]
@wangchou 
My problem is that I can not go to definition of the JS file in script blocks, I search this question any where but not solve yet, except this 'stupid extension'. you are so awesome! thanks!
