### ISSUE TITLE
Corruption of displayed text upon autocompletion.

### ISSUE THREAD

**Issue by antony** [UnwrittenFun/svelte-vscode#54]
When autocompletion closes a tag, the text gets overwritten with random utf characters. This gets immediately worse if you keep going, so a restart is required.

This neccessitates a restart after every html tag created!

If there is any information I can provide, I'd be happy to do it.

![ezgif-2-6c88d7cf97aa](https://user-images.githubusercontent.com/218949/60088277-54e78d00-9736-11e9-8c91-f5b817e04497.gif)

![giba](https://user-images.githubusercontent.com/218949/60087865-b3f8d200-9735-11e9-90e3-a46cf0e0ecf5.png)

**Comment by pngwn** [comment]
This is not linux only, I also get this bug sometimes (macOS).

**Comment by kustom666** [comment]
Can confirm this happens on windows as well

**Comment by vectorlit** [comment]
I have this problem on systems running Ubuntu 19.04, Opensuse Tumbleweed, and Windows 10 1903.
