### ISSUE TITLE
Using rules and config from .eslintrc.js

### ISSUE THREAD

**Issue by frederikhors** [UnwrittenFun/svelte-vscode#56]
I have

```js
{
  "extends": "standard"
}
```

(which comes from https://github.com/standard/eslint-config-standard#usage) in my `.eslintrc.js` and I'm wondering why this doesn't work in `<script></script>` part of my `.svelte` files.

What rules is this plugin following?

**UPDATE:**

**Reproduction project**: https://github.com/frederikhors/svelte3-vscode-eslint

Using this in command line: `npx eslint --fix .\src\*` works good, it changes `App.svelte` and `main.js` as I want: following `standard.js` rules.

**Comment by jadwahab** [comment]
I wanted to get standard rules as well and had to use https://github.com/sveltejs/eslint-plugin-svelte3 but it issue is that to get it working it needs VS Code to associate svelte files as html so it messes up the way the extension reads the svelte file.

Did you manage to get standard rules with this extension working through a better way?
