### ISSUE TITLE
Typescript is work, but Intellisense is sacrificed

### ISSUE THREAD

**Issue by hmmhmmhm** [UnwrittenFun/svelte-vscode#57]
![1](https://user-images.githubusercontent.com/38493722/60394499-5f53bd80-9b60-11e9-8c1e-0e151fd8ce24.png)

Hello, is there anyone who knows how to write typescripts on svelte-vscode and not break the intellisense? I succeeded in using typescripts in the svelte file, and I was able to see them in the vscode.....

But Intellisense has been sacrificed, 

Even a simple typescript syntax does not suggested. It's really good that error messages don't appear, and it's good that type scripts are interpreted, but can't we use Intellisense as well?

**Comment by hmmhmmhm** [comment]
![4](https://user-images.githubusercontent.com/38493722/60395298-831d0080-9b6c-11e9-9c9b-fc5f5c6b33a7.png)
![3](https://user-images.githubusercontent.com/38493722/60395299-831d0080-9b6c-11e9-94a1-abda50170c4b.png)
![2](https://user-images.githubusercontent.com/38493722/60395300-83b59700-9b6c-11e9-9e0c-9c5c0782bfd1.png)

More precisely, objects defined in the code internally appear to be highlighted, but objects in the module to be imported or basic types are not highlighted.

**Comment by numfin** [comment]
is there any updates on this?
