### ISSUE TITLE
0.9.2 is broken?

### ISSUE THREAD

**Issue by Zerowalker** [UnwrittenFun/svelte-vscode#60]
The latest 0.9.2 seems to be broken, it doesn't seem to start the language server,
and no diagnostic info is available.

What still works though is the syntax highlighting so that's something:P

**Comment by ghost** [comment]
Me too. Sass syntax in style tags is showing squiggly red lines for non-standard CSS (for example, nested statements). I added my node path language-server runtime but it makes no difference. 

<img width="621" alt="image" src="https://user-images.githubusercontent.com/1619743/64079787-aebd8380-cca0-11e9-8237-d9fbaeb2eaa7.png">

**Comment by jamesbirtles** [comment]
@cp-sean Try following this new setup guide for scss https://github.com/UnwrittenFun/svelte-vscode/blob/master/docs/preprocessors/scss.md

**Comment by ghost** [comment]
Thanks! I ended up figuring it out and even wrote a little post about my adventures. In case it helps someone else, it's here: https://medium.com/@sean_27490/svelte-sapper-with-sass-271fff662da9
