### ISSUE TITLE
button tag autocloses when entering a function

### ISSUE THREAD

**Issue by opensas** [UnwrittenFun/svelte-vscode#62]
If I start to type the following in a svelte component

```
<button>
```

Emet closes the button automatically, which is fine, the problem is when I enter a funciton to handle a click:

```
<button on:click={() =></button>
```

As soon as I type the `>` to complete the `() =>` emmet (I guess it's emmet) autocloses once againg the button, ending up like this

```
<button on:click={() =></button>}></button>
```

Here's a small video:

![vscode_svelte_emet_bug](https://user-images.githubusercontent.com/481687/61517659-262fa000-a9de-11e9-8fd8-14570e3b0efa.gif)

**Comment by soapdog** [comment]
Happens to me as well.

**Comment by jamesbirtles** [comment]
FYI you can set the `svelte.plugin.html.tagComplete.enable` setting to false until this is resolved

**Comment by opensas** [comment]
great tip!

all I had to do is ctrl-shift-p, user settings, search for `svelte tag` and disable it

**Comment by subz390** [comment]
Thanks for the workaround @UnwrittenFun - looking at `/src/html/autoClose.ts` nothing jumps out at me as a quick patch or I'd help out and do a PR, but there again I'm not familiar with that part of the VSCode codebase.  What do you think?  There's two places where this issue arises.

1. when the first `>` is typed after an opening tag
2. when `<tag ... ()=>{...}` already exists, then autoClose assumes the tag is closed

In both cases autoClose needs to be told to ignore something like `{ => }`  

Edit: I also noticed that somewhere in the source code it recognises and ignores the contents within quotes.  For example, `<tag on:click="{()=>{}}"` won't trigger the premature autoClose, and neither will it affect the detection of an already open tag.  

There is also a bug related to this - detecting an already open tag - where it reports, if I remember correctly that I'm trying to close an already closed tag but the tag is open.  The next time I get the issue I'll dig around to see where it's at and update here about it as I'm sure it's related somehow.

**Comment by skdigital** [comment]
An aside, when opening a div, the cursor jumps to the bottom of the second lower dive when pressing return. Normally when pressing return in between two divs the cursor should indent and stay on a newline in between the two divs as they open. Wondering if this issue could be fixed at the same time? :)

**Comment by jzillmann** [comment]
Facing the same issue. But even worse for me it breaks the coloring. Like everything after the inline function is just gray...

<img width="473" alt="coloring" src="https://user-images.githubusercontent.com/148472/69102594-2c548c80-0a63-11ea-9087-e0d02cf39c49.png">

Do you guys have this as well ?
