### ISSUE TITLE
.svelte has no default export for typescript

### ISSUE THREAD

**Issue by numfin** [UnwrittenFun/svelte-vscode#64]
Nothing special, just <script lang="typescript">
The same issue was with js #38 , but there is no word about ts

![image](https://user-images.githubusercontent.com/8134947/62804730-d03eab80-baf6-11e9-9a29-bea596bd45f2.png)

What i am doing wrong?

**Comment by numfin** [comment]
![image](https://user-images.githubusercontent.com/8134947/62806344-480ed500-bafb-11e9-83ba-e3010bfff69e.png)

this helped me, but idk if i did right thing 😂

**Comment by numfin** [comment]
@UnwrittenFun please my love. I hope you'll help me with this

**Comment by n10v** [comment]
Same for me

**Comment by kaisermann** [comment]
Have you tried adding `svelte` to your `tsconfig.json` `compilerOptions.types`?

**Comment by Zerowalker** [comment]
Is there any solution to this yet?
It's kinda odd cause ".ts" files handles ".svelte" files correctly based on the ".d.ts".
But when you import a ".svelte" file from within a ".svelte" file it seems to ignore it.

**Comment by danawoodman** [comment]
Any updates to this?

**Comment by numfin** [comment]
Since i'am not a svelte developer, and they don't give a damn about ts users. I'm closing this issue because i'am not using svelte since I created this issue.

**Comment by danawoodman** [comment]
Unfortunately the poor TS support is my major hurdle in adopting Svelte. I just can't give up the power TS gives me to warrant using such a (cool) tool 😢 I realllllly want to start using Svelte, but until TS is properly supported, I'll have to keep using React.

**Comment by vmohir** [comment]
@danawoodman This is just an error in VS Code. Bundlers will work. Just ignore the error.

**Comment by danawoodman** [comment]
@gvmohzibat is there a particular VS Code ticket you're aware of for this? If the TS support in `.svelte` files was there, I would give things another look.
