### ISSUE TITLE
TypeScript preprocessing is Slow

### ISSUE THREAD

**Issue by alixaxel** [UnwrittenFun/svelte-vscode#65]
Following up from https://github.com/UnwrittenFun/svelte-vscode/issues/29#issuecomment-519742347, I have a very simple `svelte.config.js` file:

```js
const { preprocess } = require('@pyoner/svelte-ts-preprocess');

module.exports = {
  preprocess: preprocess(),
};
```

The problem is that the TS transpilation takes place on every key down, which is slow:

![ezgif com-optimize](https://user-images.githubusercontent.com/262782/62811363-4a702f80-baf9-11e9-896d-7ae37f111716.gif)

You can see it underlines **n**, then **u** and then it just completes (?) - which is also weird because the return type of that call is always a `string` and therefore I think the whole line should be errored out?

```ts
interface Person {
  firstName: string;
  lastName: string;
}

export function greeter(person: Person) {
  return person.firstName + " " + person.lastName;
}
```

But the above is actually quite acceptable, but there were times where I've had to way over 5 seconds after typing to actually stop seeing the red error underlining jumping from character to character.

I'm not sure why I can't replicate that sort of condition right now, perhaps my system is not as overloaded as it usually is (and therefore transpilation is snappier) or perhaps it's just the type/amount of code that I wrote for this simple demo.

I've tried debouncing, but preprocessing just seems to stop working:

```js
const { debounce } = require('lodash');
const { preprocess } = require('@pyoner/svelte-ts-preprocess');

module.exports = {
  preprocess: (() => _.debounce(preprocess, 500))(),
};
```

Would be nice to have a better/faster developer experience on this.

**Comment by jamesbirtles** [comment]
Hopefully performance should be a little better in 0.9.3 as thing no longer run on every keystroke, closing this but let me know how it feels now
