### ISSUE TITLE
when i doing inline function like : 

### ISSUE THREAD

**Issue by ghost** [UnwrittenFun/svelte-vscode#68]
on:click={()=>dispatch('select',0)}

for example :
 <button type="button" on:click={()=>dispatch('select',0)}>All</button>

after i doing the arrow,  there is a bad autocomplete ! it closed automaticly the button tag inside the function !

(i'm working on linux mint)

**Comment by jamesbirtles** [comment]
Duplicate of #62

Closing this one in favour of that one
