### ISSUE TITLE
Request: allow comments to be at the top of the file

### ISSUE THREAD

**Issue by jcollum** [UnwrittenFun/svelte-vscode#72]
If I put `<!-- comment here --> ` at the top of the file it will get moved to the html portion of the file. It would be better if I could put those comments at the top of the file. Is this a svelte-vscode thing or a prettier thing with svelte?

**Comment by Bellarmine-Head** [comment]
Yes.  All my code files have a comments block at the top.  Formatting a .svelte doc with `svelte-vscode` moves the comments down, to be just above the HTML.

So can you have the HTML first, and the script section second?  No: formatting the doc will restore the normal script-then-HTML order.

Also: formatting the doc should respect leading and trailing blank lines (i.e. leave them alone), as is done when formatting JS files.

**Comment by Bellarmine-Head** [comment]
Ok, here's the fix, courtesy of the readme file from https://github.com/UnwrittenFun/prettier-plugin-svelte and the excellent work done by @UnwrittenFun 

Create file `.prettierrc` in your Svelte project, at the same level as the `package.json` file.  Give it these contents:-

```
{
  "svelteSortOrder" : "markup-scripts-styles",
  "svelteStrictMode": true,
  "svelteBracketNewLine": true,
  "svelteAllowShorthand": false
}
```

The important line is of course `"svelteSortOrder" : "markup-scripts-styles",`

Close VS Code, then re-open.

Now when we format a .svelte doc, the markup will come first, and a `<!-- -->` comment block will be placed above the markup, i.e. at the top of the file.  You can even have one (but not more than one) blank line separating the comments from the HTML.
