### ISSUE TITLE
Appears to be incompatable with Prettier extension

### ISSUE THREAD

**Issue by SteveALee** [UnwrittenFun/svelte-vscode#73]
Without the prettier extension installed .svelte files are formated on save. But obviously not using my prettier and editorconfig settings.

With the prettier extension installed thay are not and an error appears in the status bar saying prettier cannot format the file.

I tried disabling prettier for svelte lang id but it made no difference

I tried setting the svelte extension to be the default formatter for svelte language but the svelte extension is not a valid option. THis is suggesed in #48 but no longer seems ot be possible.

So I'm seem to be stuck using prettier for most files and svelte language service for svelte components.

I wonder if it is partly because prettier extension auto adds any plugins it finds in node_modules?

**Comment by danawoodman** [comment]
Same issue. If I enable Prettier for svelte files by passing:

```json
  "files.associations": {
    "*.svelte": "html"
  },
```

to my VSCode settings, all VSCode Svelte syntax highlighting breaks, but then I have no source formatting with Prettier.

Any way to have both?

**Comment by SteveALee** [comment]
@danawoodman I don't recall the details right now but I eventually got things working after much "sweat and tears" in this [svelte-code-cypress-project template](https://github.com/SteveALee/svelte-code-cypress-project). The readme has details of open issues addressed.

Perhaps I should submit this to [awesome-svelte](https://github.com/CalvinWalzel/awesome-svelte).

**Comment by danawoodman** [comment]
@SteveALee nice, will give this a look 👍
