### ISSUE TITLE
setting to enable svelte-strict-mode of the prettier sub-plugin ?

### ISSUE THREAD

**Issue by 0gust1** [UnwrittenFun/svelte-vscode#76]
By default this plugin autocloses non-void tags, e.g.  `<div></div>` becomes `<div />`, which is invalid, and can lead to bad habits of beginner front-end developers after they leave a svelte codebase.

Could this plugin expose the `svelte-strict-mode`flag of https://github.com/UnwrittenFun/prettier-plugin-svelte ?

**Comment by jamesbirtles** [comment]
Right now you can only configure the prettier plugin using [prettier's default config handling](https://prettier.io/docs/en/configuration.html).

E.g. create a `.prettierrc` in your project root
```json
{
    "svelteStrictMode": true
}
```

And then hit `ctrl-shift-p` or `cmd-shift-p` on mac, type `svelte restart`, and select `Svelte: Restart Language Server`

**Comment by mvolkmann** [comment]
I tried this. Now when I run "Format Document" on a .svelte file I get:
"ESLint: ESLint configuration in .eslintrc.json is invalid: - Unexpected top-level property "svelteStrictMode".
