### ISSUE TITLE
Cannot suppress import warnings inside script tags.

### ISSUE THREAD

**Issue by mattwaler** [UnwrittenFun/svelte-vscode#79]
Whenever importing components into other components, I am unable to disable these warning dots in all of my components. See screenshot below. You can see I am using the `Homepage` component inside my route.

![Screen Shot 2019-10-01 at 8 42 30 AM](https://user-images.githubusercontent.com/32300026/65962959-bdc25d80-e427-11e9-85ec-f043e36453fa.png)

The following settings did not work:
- `"javascript.validate.enable": false`
- `"html.validate.scripts": false,`

**Comment by kaisermann** [comment]
You need to set the extension diagnostic options to`false`, not `vscode` default ones: 

i.e

```json
"svelte.plugin.css.diagnostics.enable": false,
"svelte.plugin.typescript.diagnostics.enable": false,
```

**Comment by mattwaler** [comment]
Changing `"svelte.plugin.typescript.diagnostics.enable": true` and completely restarting VS Code fixed this. Do you think enabling typescript diagnostics by default is a good idea? I would think most people would probably be using Svelte with vanilla JS first, before adding in Typescript.

**Comment by kaisermann** [comment]
Great to know! 

About enabling typescript diagnostics: it's nice to have at least inferred types, even if you're using `js` 😁
