### ISSUE TITLE
PostCSS support

### ISSUE THREAD

**Issue by ghost** [UnwrittenFun/svelte-vscode#81]
Hey, I am trying to get PostCSS via `<style lang="postcss">` to work with this plugin but the documentation on this topic seems rather sparse and makes no mention of PostCSS.

Is it possible to use VS Code with PostCSS or will that not work? Right now, VSCode does not recognize PostCSS and treats it as normal CSS, resulting in errors all over the file. Does anyone have experience with PostCSS in combination with this plugin or would any pointers as to how to get it to work?

**Comment by lahickey** [comment]
Try following this suggestion: https://github.com/UnwrittenFun/svelte-vscode/issues/47#issuecomment-498883580

This should really be detailed in the README

**Comment by kaisermann** [comment]
@lahickey It is since #80 😁

**Comment by lahickey** [comment]
Aha, so it is :)

**Comment by vkrbt** [comment]
Nesting is not supported in styles with `type="text/postcss"` and `lang="postcss"`. Is it possible to use it now?

my `svelte.config.js`
```javascript
const preprocessOptions = {
    transformers: {
        postcss: {
            plugins: [
                require('postcss-import')(),
                require('postcss-nested')(),
            ],
        },
    },
};

module.exports = {
    preprocess: require('svelte-preprocess')(preprocessOptions),
};
```

**Comment by skad0** [comment]
also have problem with nested:

```javascript
import sveltePreprocess from 'svelte-preprocess'

export default {
    preprocess: sveltePreprocess({
        postcss: {
            plugins: [
                require('postcss-nested')(),
                require('autoprefixer')(),
            ]
        }
    }),
}

```

**Comment by julienchazal** [comment]
Same problem here with [Sapper](https://sapper.svelte.dev)
It would be great to had support to Sapper where `preprocess`config lives in `rollup.config.js` or `webpack.config.js`, WITHOUT having to write `type="text/postcss"` or `lang="postcss"`
Thx !

**Comment by ozzym1096** [comment]
If anyone is still seeing warnings about nested selectors (I was seeing css-rcurlyexpected), you can set svelte.plugin.css.enable to false. I think the Svelte plugin already handles warnings and diagnostics for component styles.
