### ISSUE TITLE
BUG: Incorrect HTML auto-formatting

### ISSUE THREAD

**Issue by scottjmaddox** [UnwrittenFun/svelte-vscode#82]
```
<h2>(Early Access<span style="font-size:0.9em">s</span><span style="font-size:0.8em">s</span><span
              style="font-size:0.7em">s</span><span style="font-size:0.6em">s</span><span
              style="font-size:0.5em">s</span><span style="font-size:0.4em">s</span>)</h2>
```

gets reformatted to

```

      <h2>
        (Early Access
        <span style="font-size:0.9em">s</span>
        <span style="font-size:0.8em">s</span>
        <span style="font-size:0.7em">s</span>
        <span style="font-size:0.6em">s</span>
        <span style="font-size:0.5em">s</span>
        <span style="font-size:0.4em">s</span>
        )
      </h2>
```

which is semantically different because it includes spaces between the spans.

On a related note, is there a way to selectively skip reformatting of some HTML as a workaround? I tried `<!-- prettier-ignore -->`, but it doesn't seem to work.

**Comment by mdorda** [comment]
I am facing the same issue:

```html
... abc text <a href="#">link</a>. Another text ...
```

has an output: `... abc text link. Another text ...`

But after auto formatting into:

```html
... abc text
<a href="#">link</a>
. Another text ...
```
is the output: `... abc text link . Another text ...` (with a space between link and dot)

**Comment by jasonlyu123** [comment]
related issue on prettier-plugin-svelte
https://github.com/UnwrittenFun/prettier-plugin-svelte/pull/41
https://github.com/UnwrittenFun/prettier-plugin-svelte/issues/59

**Comment by schneyra** [comment]
I'm having the same problem and could not yet find a working workaround. Any ideas?
