### ISSUE TITLE
Selector is expected

### ISSUE THREAD

**Issue by 0x000777** [UnwrittenFun/svelte-vscode#85]
![image](https://user-images.githubusercontent.com/17083227/67392502-54a6b380-f5a9-11e9-9124-91d4d9872e21.png)

I use SCSS (svelte-preprocess). The screenshot shows a syntax error, in fact, everything is correctly written without errors.
Can you add a rule to prevent this error when using scss?

**Comment by kaisermann** [comment]
@Highter87 Hey! Have you configured a `svelte.config.js` file on the root of your project?

**Comment by 0x000777** [comment]
Strange, I had it ... But in fact this configuration file did not exist.
The issue is resolved!
