### ISSUE TITLE
Make printWidth option configurable

### ISSUE THREAD

**Issue by Niek** [UnwrittenFun/svelte-vscode#91]
The ``printWidth`` option of prettier is currently set to 100: https://github.com/UnwrittenFun/svelte-vscode/blob/a40e28ce26c7e7ef395190d53f25e8ae4c5725b2/.prettierrc#L3

It would be great if this could be made configurable. In my opinion 100 is way too low, if you have 4-5 nested HTML tags the text will be broken every word or so.

**Edit**: I just noticed that dropping a custom ``.prettierrc`` in the project root dir and reloading VSCode works as well. Still, it'd be nice if this could be configured through a VSCode preference.

**Comment by mvolkmann** [comment]
Of course we will never please everyone. I prefer 80. I'd much rather have a default of 100 than something higher. This is because I very frequently edit files side-by-side.

**Comment by Niek** [comment]
Hence the request to make it configurable, not to change the default 😉
