### ISSUE TITLE
Odd formatting issue with @html

### ISSUE THREAD

**Issue by dkodeit** [UnwrittenFun/svelte-vscode#94]
![SharedScreenshot](https://user-images.githubusercontent.com/39446969/70905591-1cc05900-1fb9-11ea-833d-229c362a7ade.jpg)

When formatting, the top line results in the bottom line. Formatting replaces the contents with ✂prettier:content✂

This issue is related to the enable formatting for svelte (includes css & js) option. If enabled, the issue happens.

**Comment by 2234839** [comment]
I had the same problem
So I had to use the cumbersome ones 「+」＆「"」
